### ISSUE TITLE
Uh

### ISSUE THREAD

**Issue by vutondesign** [TMNarula/TeamHouse#1]
This has just been taken straight from Wikipedia, so you can't really claim it as your own work in a repo.

**Comment by redmangospros** [comment]
This IS A REAL EASTE COMPANY REPO. AS SAID, NO ISSUES.
I Know, i never said it's my.
this is for my parents rea; easte company.

DO NOT CREATE A ISSUE!

**Comment by vutondesign** [comment]
Yeah, I understand that. However two things:

1) If you don't want issues and pull requests, Github isn't the right place for this.
2) Even if you didn't say you own it, You have to credit Wikipedia and the original owners of this work.

**Comment by redmangospros** [comment]
oringal owners

**Comment by vutondesign** [comment]
What do you mean by original owners?

**Comment by redmangospros** [comment]
What do you mean by iit?
I'm The online manger for this org

**Comment by vutondesign** [comment]
I know you are but your not the online manager of Wikipedia, and you didn't write that description in the readme.

**Comment by redmangospros** [comment]
i'm the online manger of This Org TMNarula/TMNarula.github.io/#1
I Did Write that, i looked at it and wrote it

**Comment by vutondesign** [comment]
No, You copy-and-pasted it and I can tell as It still has the original Wikipedia notes and references in it.

**Comment by redmangospros** [comment]
no i didn't

**Comment by vutondesign** [comment]
You did, as I said above it still has the original Wikipedia notes and references in it.

**Comment by redmangospros** [comment]
Sorry, I Created a repo saying don't belive @vuton 
But I Did By Mistake, I Got a bit mad, sorry!

**Comment by vutondesign** [comment]
Okay, I'll just go now...

**Comment by redmangospros** [comment]
no, don;t.
i'm sorry, itjust i'm working so hard and getting tired.
But, I can repay you by making a issue by saying follow yoi

**Comment by vutondesign** [comment]
I really don't mind.

**Comment by redmangospros** [comment]
Oh, you won't report me?

**Comment by vutondesign** [comment]
Uh, No...

**Comment by redmangospros** [comment]
Thanks.

**Comment by redmangospros** [comment]
Please Do not reply
